Create Binary Search.py
Ryuji-Facilities/Coding-challenge pull request #17
Opened 2022-10-10 19:53 UTC by tinyCodersDen

Solution to code for implementing Binary Search in Python.

2022-10-10 22:48 UTC, its0din-ai requested changes
remove the array length subtraction
and set the target to 101 (last index)

2022-10-10 22:48 UTC, its0din-ai commented on Python/Binary Search.py
> +BinarySearch(0,len(elements)-1)
Why the length of elements is subtracted by 1?
Because if the length is subtracted by 1. we cannot find 101 as the target

2022-10-10 23:06 UTC, its0din-ai commented
And catch the Error if target isn't present on the array

2022-10-10 23:31 UTC, its0din-ai commented
We will take over the code at 10 AM (GMT)

2022-10-10 23:37 UTC, dvoraksz reviewed
Catch the error

2022-10-11 10:09 UTC, its0din-ai approved these changes

2022-10-11 10:09 UTC, merged

2022-10-11 10:09 UTC, its0din-ai commented
**THANKS FOR PARTICIPATING**