Create hacktoberfest.py
Ryuji-Facilities/Coding-challenge pull request #6
Opened 2022-10-02 07:30 UTC by pavitra1129

this program will print hacktoberfest 2022 for 1000 times

2022-10-02 10:28 UTC, its0din-ai commented
We Will merge this If you can add an Indexing,
like :
0. Hacktoberfest
1. Hacktoberfest
...

2022-10-02 10:29 UTC, its0din-ai requested changes
Add for loops Indexing

2022-10-06 06:40 UTC, its0din-ai commented
If there's no Respond in 24 Hours, We will mark this as Spam

2022-10-09 13:48 UTC, pavitra1129 commented
here is the code you wanted sorry for responding late but here is the code you wanted please remove the spam label
for i in range(0,1001):
    p = str(i)
    print(p+'''. hacktoberfest 2022''')

2022-10-09 13:49 UTC, pavitra1129 commented
please remove the spam label

2022-10-09 13:50 UTC, its0din-ai requested changes
modify this

2022-10-09 13:51 UTC, pavitra1129 commented
sir is this ok

2022-10-09 13:52 UTC, pavitra1129 commented
or you want any other change

2022-10-09 13:53 UTC, its0din-ai commented on Python/hacktoberfest.py
> + print("hacktoberfest 2022"*1000)
Ask for user input, then loop the "Hacktoberfest2022" according to the input

2022-10-09 13:56 UTC, its0din-ai approved these changes

2022-10-09 13:59 UTC, merged